#Database
POSTGRES_SQL_USERNAME: root
POSTGRES_SQL_PASSWORD: 0000
POSTGRES_SQL_HOST: localhost
POSTGRES_SQL_PORT: 3306
POSTGRES_SQL_DB: mybase

#Server
SERVER_PORT: 8086
ACTIVE_PROFILE: dev

#Email Config
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: <YOUR EMAIL ADDRESS>
EMAIL_PASSWORD: <YOUR PASSWORD>
VERIFY_EMAIL_HOST: http://localhost:${SERVER_PORT}